### ISSUE TITLE
Ignore label question，标签处理问题

### ISSUE THREAD

**Issue by LEE-cm** [liminn/ICNet#14]
Cityscapes dataset, I changed the ignored label from the original -1 to 255 in original script and Correspondingly changed the loss function's ignore label, but meet errors.
为什么处理cityscapes数据集时把忽略的标签都设为-1，在计算损失函数时resize用的双线性差值不报错。当我把忽略标签改为255，计算损失函数就会报错，把插值方式改为近邻插值就没事了。

**Comment by liminn** [comment]
抱歉，由于工作原因很少有时间维护该git。
我猜测是双线性差值会改变像素值，比如出现254或253等lable中不存在的值。
