### ISSUE TITLE
Retrained model

### ISSUE THREAD

**Issue by omidhm** [liminn/ICNet#16]
"icnet_resnet50_197_0.710_best_model.pth"  is not exist?

**Comment by nguyentritai2906** [comment]
You can download it [here](https://drive.google.com/file/d/1fPOPM19Mp4tpiaeslFgoV5ELFprdxTDl/view?usp=sharing)

**Comment by liminn** [comment]
refer to this issue: https://github.com/liminn/ICNet-pytorch/issues/2#issuecomment-747436349
I upload the  "icnet_resnet50_197_0.710_best_model.pth" here, thanks.
