### ISSUE TITLE
How can i get the pretrained model?

### ISSUE THREAD

**Issue by yemika** [liminn/ICNet#2]
How can i get the pretrained model

**Comment by liminn** [comment]
@yemika  hi, I will update the model link next week.

**Comment by absorbguo** [comment]
> @yemika hi, I will update the model link next week.

Hi the model link in the Readme seems broken，Could you update this link，many Thanks~

**Comment by Joyies** [comment]
@absorbguo  
Hi the model link in the Readme seems broken，Could you update this link

**Comment by qiaoyaya2011** [comment]
@liminn Hi the model link in the Readme seems broken，Could you update this link

**Comment by fnbory** [comment]
@liminn Hi the model link in the Readme seems broken，Could you update this link

**Comment by liminn** [comment]
Sorry to reply so late, this is the pretrained weights link: 
- link: https://pan.baidu.com/s/1sX8FO4RtVxlmMxAFudgLpw 
- passwork: rcki
