### ISSUE TITLE
Number of parameters

### ISSUE THREAD

**Issue by erichhhhho** [liminn/ICNet#3]
The number of parameters for your implemented model is 28298376, which is much more than the official.

**Comment by liminn** [comment]
@erichhhhho hi, I will check the parameters you said. How do you get the number of parameters of the official model?

**Comment by erichhhhho** [comment]
@liminn it is around 7.8M

**Comment by erichhhhho** [comment]
@liminn May I ask in this code, you train the model from scratch or from the pretrained?

**Comment by liminn** [comment]
Not from scratch, because backbone used pretrained weights
