### ISSUE TITLE
Question about sub2 and sub4 share three phases convolution.

### ISSUE THREAD

**Issue by SecondLi** [liminn/ICNet#4]
Thank you for your codes.
I run your code and get a better results,but when I check the code, I am confused ahout the following code:
        # sub 2
        x_sub2 = F.interpolate(x, scale_factor=0.5, mode='bilinear', align_corners=True)
        _, x_sub2, _, _ = self.base_forward(x_sub2)
        # sub 4
        x_sub4 = F.interpolate(x, scale_factor=0.25, mode='bilinear', align_corners=True)
        _, _, _, x_sub4 = self.base_forward(x_sub4)
In the paper and your discussion , it explains that sub2 and sub4 will share the weights and computation, but in your code, you just put the 1/2 and 1/4 image to the basemodel, am I right?
how do your share the weights and convolution or how do your understand the definition of the share.

**Comment by liminn** [comment]
@SecondLi  Hi, no thanks.
In my opinion, the definition of the "share" is: 
- Define the parameters once,  and update them repeatedly.
