### ISSUE TITLE
hi  Could you upload the 0.71 pre training model again 

### ISSUE THREAD

**Issue by lbhnoteatfish** [liminn/ICNet#5]
Could you upload the 0.71 pre training model again 。The link is invalid！ thank you！

**Comment by Artashes00** [comment]
Yes, The link is invalid. Please update

**Comment by absorbguo** [comment]
Hi， the pretrained model link is invalid

**Comment by liminn** [comment]
I have upload pre-trained weights. The code in the repository can be directly trained, you can contact me if you have any problems, thank you.
#2
