### ISSUE TITLE
download resnet50

### ISSUE THREAD

**Issue by XU-GITHUB-curry** [liminn/ICNet#8]
when I use 'python3 train.py' as readme.
 __error :__

Downloading /home/abc/.torch/models/resnet50-25c4b509.zip from https://hangzh.s3.amazonaws.com/encoding/models/resnet50-25c4b509.zip...
Traceback (most recent call last):
  File "train.py", line 229, in <module>
    trainer = Trainer(cfg)
  File "train.py", line 45, in __init__
    self.model = ICNet(nclass = train_dataset.NUM_CLASS, backbone='resnet50').to(self.device)
  File "/home/abc/guoanXu/ICNet-master/models/icnet.py", line 16, in __init__
    super(ICNet, self).__init__(nclass,backbone, pretrained_base=pretrained_base)
  File "/home/abc/guoanXu/ICNet-master/models/segbase.py", line 22, in __init__
    self.pretrained = resnet50_v1s(pretrained=pretrained_base, dilated=dilated, **kwargs)
  File "/home/abc/guoanXu/ICNet-master/models/base_models/resnetv1b.py", line 239, in resnet50_v1s
    model.load_state_dict(torch.load(get_resnet_file('resnet50', root=root)), strict=False)
  File "/home/abc/guoanXu/ICNet-master/models/model_store.py", line 51, in get_resnet_file
    overwrite=True)
  File "/home/abc/guoanXu/ICNet-master/utils/download.py", line 68, in download
    raise RuntimeError("Failed downloading url %s"%url)
RuntimeError: Failed downloading url https://hangzh.s3.amazonaws.com/encoding/models/resnet50-25c4b509.zip
how to solve it please?

**Comment by qiaoyaya2011** [comment]
I also meet this problem,Failed downloading url https://hangzh.s3.amazonaws.com/encoding/models/resnet50-25c4b509.zip
can u solve it ? @XU-GITHUB-curry @liminn

**Comment by swjtulinxi** [comment]
请问batchsize对结果的影响大还是cropsize，因为我只有一张卡，我发现我无论用什么上下文模块，ppm，aspp注意力，等，发现加不加都没啥区别

**Comment by Bigpingping97** [comment]
I also meet this problem,Failed downloading url https://hangzh.s3.amazonaws.com/encoding/models/resnet50-25c4b509.zip
can u solve it ? @XU-GITHUB-curry @liminn

**Comment by XU-GITHUB-curry** [comment]
no，I haven't solved it.





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Bigpingping97"<notifications@github.com&gt;; 
发送时间: 2021年3月8日(星期一) 晚上7:14
收件人: "liminn/ICNet-pytorch"<ICNet-pytorch@noreply.github.com&gt;; 
抄送: "Dr Sco."<1061053760@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [liminn/ICNet-pytorch] download resnet50 (#8)





 
I also meet this problem,Failed downloading url https://hangzh.s3.amazonaws.com/encoding/models/resnet50-25c4b509.zip
 can u solve it ? @XU-GITHUB-curry @liminn

**Comment by nguyentritai2906** [comment]
You can download it [here](https://drive.google.com/file/d/1KcVMI928F_bCpP6wsavBqI_ef91ceZhb/view?usp=sharing)
