### ISSUE TITLE
请问这个可以做视频分割吗，没看见有代码啊

### ISSUE THREAD

**Issue by swjtulinxi** [liminn/ICNet#9]

**Comment by swjtulinxi** [comment]
你好，请问是batchsize对精度影响大，还是cropsize，因为我只有一张2080ti，我用你这个代码训练pspnet，cropsize设置为768，那么batchsize只能设置2，，如果cropsize设置为512，那么batchsize只能设置为4，，请问用哪个设置好点啊

**Comment by liminn** [comment]
只在citycapes图像数据集上进行了实验，如果做视频分割的话，需要自己写inference脚本。
建议cropsize=768，batchsize=2。
